server:
  name: Burr
  domain: "example.localhost"
secrets:
  addr: "http://127.0.0.1:8200"
db:
  driver: "sqlite"
redis:
  driver: "dev"
  addr: "http://127.0.0.1:6379"
faktory:
  bind: "http://127.0.0.1:7419"
