FROM golang:alpine as build
ENV CI=true

WORKDIR /build
RUN apk add -U upx git musl-dev gcc make
COPY . .
RUN make test

#FROM scratch
#COPY --from=build /build/server /server
#WORKDIR /data
#ENTRYPOINT [ "/server" ]
