name: docker

on:
  push:
    branch: [master]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Docker
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - run: |
          make docker
      - uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b #v2.0.0
        with:
          registry: ghcr.io
          username: eriner
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker push ghcr.io/eriner/burr:latest
